services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vpndan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb:latest
    restart: unless-stopped
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:postgres@postgres:5432/vpndan?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  pgdata:
